"""aggiunto umore

Revision ID: 9796a8bdbce6
Revises: 06a896db6c23
Create Date: 2025-09-15 09:16:02.930339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9796a8bdbce6'
down_revision = '06a896db6c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('umore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stato', sa.String(length=80), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stato')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('umore')
    # ### end Alembic commands ###
